project_id = "icmhwdrchtvoqldhdwze"

[functions.analyze-product-photo]
verify_jwt = true

[functions.send-otp]
verify_jwt = false

[functions.send-confirmation-email]
verify_jwt = false

[functions.admin-clear-cache]
verify_jwt = true
